### ISSUE TITLE
UI/UX: Styling: Update buttons' color

### ISSUE THREAD

**Issue by thao-do** [AllenCell/allencell-segmenter-ml#432]
Update the colors of the following buttons:
#### Main screen:
- [x] [Apply] button's enabled-state: change border & fill color from grey #414851 (named "Foreground" in the default color palette) to blue #007ACC (named "Current") with hover border & fill color #41B3FF - to emphasize it

#### Curation - start screen:
- [x] [Start] button's enabled-state: change border & fill color from grey #414851 (named "Foreground") to blue #007ACC (named "Current") with hover border & fill color #41B3FF - to emphasize it

#### Curation - main screen:
- [x] [Save Curation CSV] button's enabled-state: change fill color from blue #007ACC (named "Current" in the default color palette) to grey #414851 (named "Foreground") - to de-emphasize it
- [x] All disabled buttons should have same disabled colors (also it looks like we have a couple disable button styles here that should be the same and consistent): border & fill color #414851 ("Foreground"), text fill color #6A7380. Their enabled colors stay the same respectively. 
This applies to the [+Create], [Delete] and [Save] buttons in the screenshot below.
Current____<img width="400" alt="Screenshot 2024-07-02 at 4 08 24 PM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/b3a93476-fd56-48ff-9376-a7c578d7150c">
Expected __<img width="400" alt="Screenshot 2024-07-02 at 4 03 49 PM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/28b2a6d8-d6c3-4538-8fba-828daf7315e2">

---
## Stretch
Update section border color from currently #AAAAAA to #414851 ("Foreground"). These section border appear in: 
- [x] Curation - main screen: (1) the progress bar section, (2) section of "Use this image for training..." <img width="400" alt="Screenshot 2024-07-03 at 9 55 31 AM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/4f92f26c-cb4f-4072-be50-715c496be532"><img width="200" alt="Screenshot 2024-07-03 at 9 55 36 AM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/6c6b629d-3de3-4069-a227-ede6fa648749">

- [x] Training: training images section <img width="400" alt="Screenshot 2024-07-03 at 9 55 42 AM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/e0c4d2e6-b489-4c78-bed7-0caf99a92792">

- [x] Prediction: input image(s) section <img width="400" alt="Screenshot 2024-07-03 at 9 55 48 AM" src="https://github.com/AllenCell/allencell-ml-segmenter/assets/25212364/4ef26e2b-31f6-44dd-95a2-3405cbd441b1">
